spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/document_test_db
      auto-index-creation: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/loanflow

# MinIO Configuration - Test
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: loanflow-test-documents

logging:
  level:
    com.loanflow: DEBUG
